### ISSUE TITLE
Update libadwaita colors

### ISSUE THREAD

**Issue by wroyca** [piousdeer/vscode-adwaita#18]
The Libadwaita color scheme has been updated, resulting in most of the colors being inaccurate
e.g. with tabs:

###### before
![image](https://user-images.githubusercontent.com/91024200/208006310-bc91d227-3d0d-426f-bd4e-ea1aae9f3ac5.png)

###### after
![image](https://user-images.githubusercontent.com/91024200/208007010-36fb2bb8-2af1-4b71-baae-d6eff542a036.png)

**Comment by piousdeer** [comment]
Thanks for the alert. I'll address this in a major version release along with all the other currently open issues. A lot of unfinished work has been lying stalled in my local branch, but I'll be able to continue in a few days.
