### ISSUE TITLE
Inconsistent color, size and gap, and rectangle artifact on normal, hover and active state of titlebar button

### ISSUE THREAD

**Issue by Ashvith10** [piousdeer/vscode-adwaita#21]
In this example, I'll be taking the minimize button, which is similar to both maximize and close button for GTK4 app. For VSCode (with adwaita plugin) , close button on hover and active state shows the color red, which is inaccurate. Also, there is a box outside, which listens to the click event, when it should be the button icons which should react. There's also gap and sizing inconsistency.

#### Normal state (#484848)
![Screenshot from 2023-03-06 18-54-19](https://user-images.githubusercontent.com/113123021/223123306-1580e254-42e2-457a-b061-f31702f10210.png)
#### Hover state (#4F4F4F)
![Screenshot from 2023-03-06 18-54-04](https://user-images.githubusercontent.com/113123021/223123392-7256959d-72ad-4c54-ba16-59d45a4d5db6.png)
#### Active state (#6D6D6D)
![Screenshot from 2023-03-06 18-55-23](https://user-images.githubusercontent.com/113123021/223123428-1662d839-387c-4c3b-a6bf-5129e9241ca4.png)

#### Normal state (#363636)
![Screenshot from 2023-03-06 18-55-48](https://user-images.githubusercontent.com/113123021/223123745-477b15f5-6f94-4887-b425-6fc7a5f27f38.png)
#### Hover state (#535353)
![Screenshot from 2023-03-06 18-55-57](https://user-images.githubusercontent.com/113123021/223123771-4f5540eb-b781-40ba-9d7a-e113225c962e.png)
#### Active state (#535353)
![Screenshot from 2023-03-06 18-56-11](https://user-images.githubusercontent.com/113123021/223123792-45497f04-a0bf-4581-b642-ed4b28cc7cd7.png)

#### Inconsistent size and gap.
![Screenshot from 2023-03-06 19-13-24](https://user-images.githubusercontent.com/113123021/223126928-6ff0a5ba-277f-4eaa-a9cc-12ba3bf78202.png)

**Comment by piousdeer** [comment]
Unfortunately, VS Code themes are limited to color changes, and these particular colors are hardcoded. Both this and #20 are unfixable except via injecting custom CSS, which is unsupported and likely won't be shipped with this extension anytime soon: see https://github.com/piousdeer/vscode-adwaita/issues/7#issuecomment-1256814782.

If you're willing to inject CSS, #11 contains snippets you can apply to fix the button sizes.

**Comment by Ashvith10** [comment]
@piousdeer Another solution would be to do what Microsoft Edge does with their browser - a small corner is allocated for the native title bar buttons, while the rest of it is the internal browser GUI. This has to be done in the VSCode/Electron repository however.

**Comment by adhadse** [comment]
@piousdeer Can vscode respect the titlebar decorations customized by GNOME Tweaks app, showing no maximize or minimize icon in the titlebar?

Edit:
Ahh, Issue #20

**Comment by piousdeer** [comment]
Not with `window.titleBarStyle` set to `custom`. You can create a feature request for VS Code.

**Comment by adhadse** [comment]
@piousdeer @Ashvith10 Raised [#176467](https://github.com/microsoft/vscode/issues/176467)
