### ISSUE TITLE
Respect Titlebar Window Actions side settings

### ISSUE THREAD

**Issue by cakePhone** [piousdeer/vscode-adwaita#24]
With the theme installed on vscode, the titlebar buttons go back to the right side:
![image](https://github.com/piousdeer/vscode-adwaita/assets/82392894/9ec7aa19-69ce-4d56-9b1b-2c6988da2c5d)

While I have them set to the left side, example on firefox:
![image](https://github.com/piousdeer/vscode-adwaita/assets/82392894/3b21d450-520a-4baf-a43c-d37025951947)

This is kinda triggering me for now. I love the theme and what it has to offer, but this is such a deal breaker for me. Please fix it.

**Comment by piousdeer** [comment]
Unfortunately, this isn't something a VS Code theme can do (see #20, #21 - there is an open feature request over at the vscode repo).

**Comment by cachandlerdev** [comment]
Is it possible that this could now be implemented, given that VSCode has implemented [native window controls](https://code.visualstudio.com/updates/v1_93#_linux-support-for-window-control-overlays) even with a custom title bar?
