### ISSUE TITLE
Mismatched title bar

### ISSUE THREAD

**Issue by YousefSaber** [piousdeer/vscode-adwaita#3]
despite installing [adw-gtk3](https://github.com/lassekongo83/adw-gtk3) VSCode still can't implement adwaita theme on title bar 

![Screenshot from 2022-04-08 13-28-06](https://user-images.githubusercontent.com/33742499/162427405-94b48def-1719-4412-9c58-1c496f4d8f30.png)

```
(base) joseph@localhost:~> ls /usr/share/themes/
Adwaita  Adwaita-dark  adw-gtk3  adw-gtk3-dark  Default  Emacs  HighContrast  Raleigh
```
my `settings.json` file
```
{
    "java.configuration.runtimes": [],
    "java.home": "/home/joseph/Downloads/OpenJDK11U-jdk_x64_linux_hotspot_11.0.7_10/jdk-11.0.7+10",
    "notebook.consolidatedRunButton": true,
    "notebook.lineNumbers": "on",
    "jupyter.askForKernelRestart": false,
    "workbench.preferredDarkColorTheme": "Adwaita Dark",
    "workbench.preferredLightColorTheme": "Adwaita Light",
    "window.titleBarStyle": "native",
    "window.menuBarVisibility": "toggle", // Menu bar will be hidden until you press Alt
    "breadcrumbs.enabled": false,
    "editor.renderLineHighlight": "none",
    "workbench.iconTheme": null,
    "workbench.tree.indent": 12,
    "workbench.colorTheme": "Adwaita Dark & colorful status bar",
}
```

**Comment by piousdeer** [comment]
VSCode can't theme the title bar when titleBarStyle is native. Enable adw-gtk3-dark: `gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark`

**Comment by YousefSaber** [comment]
@piousdeer alright I fixed it I changed some settings.
```
    "window.titleBarStyle": "custom",
```
![image](https://user-images.githubusercontent.com/33742499/162577048-00dc5cae-2973-49b5-b0c1-9ac13fb94b7c.png)
